### ISSUE TITLE
Panic in the helm chart provisioner

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/rukpak#503]
When running the main branch rukpak release, a panic is produced in the helm chart provisioner:

<details>

```log
1.6609191722125077e+09	INFO	setup	starting up the provisioner	{"git commit": "3b5e67a"}
1.660919172469351e+09	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": "127.0.0.1:8080"}
1.660919172471164e+09	INFO	setup	starting manager
1.6609191724720306e+09	INFO	Starting server	{"kind": "health probe", "addr": "[::]:8081"}
1.6609191724720716e+09	INFO	Starting server	{"path": "/metrics", "kind": "metrics", "addr": "127.0.0.1:8080"}
1.660919172472149e+09	INFO	Starting EventSource	{"controller": "bundledeployment", "controllerGroup": "core.rukpak.io", "controllerKind": "BundleDeployment", "source": "kind source: *v1alpha1.Bundle"}
1.6609191724722533e+09	INFO	Starting Controller	{"controller": "bundledeployment", "controllerGroup": "core.rukpak.io", "controllerKind": "BundleDeployment"}
1.6609191724723864e+09	INFO	Starting EventSource	{"controller": "bundledeployment", "controllerGroup": "core.rukpak.io", "controllerKind": "BundleDeployment", "source": "kind source: *v1alpha1.BundleDeployment"}
1.6609191724726954e+09	INFO	Starting EventSource	{"controller": "bundledeployment", "controllerGroup": "core.rukpak.io", "controllerKind": "BundleDeployment", "source": "kind source: *v1alpha1.Bundle"}
1.6609191724727285e+09	INFO	Starting Controller	{"controller": "bundledeployment", "controllerGroup": "core.rukpak.io", "controllerKind": "BundleDeployment"}
1.6609191725740767e+09	INFO	Starting workers	{"controller": "bundledeployment", "controllerGroup": "core.rukpak.io", "controllerKind": "BundleDeployment", "worker count": 1}
1.6609191725740683e+09	INFO	Starting workers	{"controller": "bundledeployment", "controllerGroup": "core.rukpak.io", "controllerKind": "BundleDeployment", "worker count": 1}
1.6609191725745285e+09	DEBUG	starting reconciliation	{"controller": "bundledeployment", "controllerGroup": "core.rukpak.io", "controllerKind": "BundleDeployment", "bundleDeployment": {"name":"hello-world-helm"}, "namespace": "", "name": "hello-world-helm", "reconcileID": "6d7b1480-6989-46be-89fe-9243ee609f9e"}
1.6609191725745888e+09	DEBUG	starting reconciliation	{"controller": "bundledeployment", "controllerGroup": "core.rukpak.io", "controllerKind": "BundleDeployment", "bundle": {"name":"hello-world-helm-d7wbc2"}, "namespace": "", "name": "hello-world-helm-d7wbc2", "reconcileID": "45580f73-c30c-4a28-aed7-791ddd977c9e"}
1.6609191725940704e+09	DEBUG	ending reconciliation	{"controller": "bundledeployment", "controllerGroup": "core.rukpak.io", "controllerKind": "BundleDeployment", "bundleDeployment": {"name":"hello-world-helm"}, "namespace": "", "name": "hello-world-helm", "reconcileID": "6d7b1480-6989-46be-89fe-9243ee609f9e"}
1.6609191725941677e+09	DEBUG	starting reconciliation	{"controller": "bundledeployment", "controllerGroup": "core.rukpak.io", "controllerKind": "BundleDeployment", "bundleDeployment": {"name":"hello-world-helm"}, "namespace": "", "name": "hello-world-helm", "reconcileID": "1f3c7b9e-949a-4f0b-9cf3-0d2fdceaf59b"}
1.6609191726017177e+09	DEBUG	ending reconciliation	{"controller": "bundledeployment", "controllerGroup": "core.rukpak.io", "controllerKind": "BundleDeployment", "bundleDeployment": {"name":"hello-world-helm"}, "namespace": "", "name": "hello-world-helm", "reconcileID": "1f3c7b9e-949a-4f0b-9cf3-0d2fdceaf59b"}
1.6609191746520896e+09	DEBUG	ending reconciliation	{"controller": "bundledeployment", "controllerGroup": "core.rukpak.io", "controllerKind": "BundleDeployment", "bundle": {"name":"hello-world-helm-d7wbc2"}, "namespace": "", "name": "hello-world-helm-d7wbc2", "reconcileID": "45580f73-c30c-4a28-aed7-791ddd977c9e"}
1.6609191746521125e+09	INFO	Observed a panic in reconciler: runtime error: slice bounds out of range [14:10]	{"controller": "bundledeployment", "controllerGroup": "core.rukpak.io", "controllerKind": "BundleDeployment", "bundle": {"name":"hello-world-helm-d7wbc2"}, "namespace": "", "name": "hello-world-helm-d7wbc2", "reconcileID": "45580f73-c30c-4a28-aed7-791ddd977c9e"}
panic: runtime error: slice bounds out of range [14:10] [recovered]
	panic: runtime error: slice bounds out of range [14:10]

goroutine 188 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x1def580, 0xc002b44db0})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x207
github.com/operator-framework/rukpak/internal/provisioner/helm/controllers.getChart.func1({0xc004e042f0, 0xa}, {0x22292c0?, 0xc0003ac6f0?}, {0x0?, 0x0?})
	/home/runner/work/rukpak/rukpak/internal/provisioner/helm/controllers/bundledeployment_controller.go:371 +0x32e
io/fs.walkDir({0x220cb00, 0xc0003ac590}, {0xc004e042f0, 0xa}, {0x22292c0, 0xc0003ac6f0}, 0xc0009d58a0)
	/opt/hostedtoolcache/go/1.18.5/x64/src/io/fs/walk.go:66 +0x78
io/fs.walkDir({0x220cb00, 0xc0003ac590}, {0x1f1c230, 0x1}, {0x2228920, 0xc0003ac5a0}, 0xc0009d58a0)
	/opt/hostedtoolcache/go/1.18.5/x64/src/io/fs/walk.go:85 +0x27d
io/fs.WalkDir({0x220cb00, 0xc0003ac590}, {0x1f1c230, 0x1}, 0xc0009d58a0)
	/opt/hostedtoolcache/go/1.18.5/x64/src/io/fs/walk.go:112 +0xde
github.com/operator-framework/rukpak/internal/provisioner/helm/controllers.getChart({0x220cb00?, 0xc0003ac590?})
	/home/runner/work/rukpak/rukpak/internal/provisioner/helm/controllers/bundledeployment_controller.go:348 +0x9e
github.com/operator-framework/rukpak/internal/provisioner/helm/controllers.validateChart({0x220cb00?, 0xc0003ac590?})
	/home/runner/work/rukpak/rukpak/internal/provisioner/helm/controllers/bundle_controller.go:154 +0x25
github.com/operator-framework/rukpak/internal/provisioner/helm/controllers.(*BundleReconciler).Reconcile(0xc00060d450, {0x2227810, 0xc0009864b0}, {{{0x0?, 0x10?}, {0xc00074d4d0?, 0x40d7e7?}}})
	/home/runner/work/rukpak/rukpak/internal/provisioner/helm/controllers/bundle_controller.go:136 +0x9d5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x2227768?, {0x2227810?, 0xc0009864b0?}, {{{0x0?, 0x1e36940?}, {0xc00074d4d0?, 0x4041f4?}}})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000739400, {0x2227768, 0xc0007aa500}, {0x1d01b20?, 0xc0002a0460?})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000739400, {0x2227768, 0xc0007aa500})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:230 +0x325
```

</details>

And here is the BundleDeployment resource that was used:

<details>

```yaml
apiVersion: core.rukpak.io/v1alpha1
kind: BundleDeployment
metadata:
  name: hello-world-helm
  namespace: demo1
spec:
  provisionerClassName: core-rukpak-io-helm
  config:
    values: |
      namespace: demo1
  template:
    metadata:
      labels:
        app: hello-world-helm
    spec:
      provisionerClassName: core-rukpak-io-helm
      source:
        git:
          repository: https://github.com/kube-reporting/metering-operator
          ref:
            branch: master
        type: git
```

</details>

**Comment by akihikokuroda** [comment]
The repository setting is expected to be 
``` 
repository: https://github.com/kube-reporting/metering-operator/charts
```
Some error handling code must be put to prevent the panic and reporting the status correctly.

This repository has 2 charts in it.  The provisioner is assuming only one chart.  We probably need a separate issue to support multiple charts in one bundle.

**Comment by timflannagan** [comment]
Yup, but we need to fix the panic here. What I had supplied was a misconfiguration and we'd need to be able to express that in the BD's status for a smooth UX.

**Comment by timflannagan** [comment]
> We probably need a separate issue to support multiple charts in one bundle.

IMO, this isn't something we need (or want) to support. Maybe if we get an explicit use case but it's unclear what that would be right now.

**Comment by akihikokuroda** [comment]
The source should have the `directory` but this case it still fails because of 2 charts.
```
      source:
        git:
          repository: https://github.com/kube-reporting/metering-operator
          ref:
            branch: master
          directory: ./charts
```

**Comment by timflannagan** [comment]
Moving this to the v0.9.0 milestone. This is a potential release blocker imo.

**Comment by timflannagan** [comment]
Just quickly tried to reproduce this using the same BD in the issue, and I wasn't able to after Joe's changes landed in main.
